rule dfebefddeecfffceeeaceefbf_php {
strings:
        $s1 = "'DISbHISWDHSODHSOFHSRDHSFDHSODHSODHSODHSODHSOEHSDFP9bDHSODHccJRWOM0SODHSODISOHHSXEHSODHAE' , "
        $s2 = "'ETcOHHSODHSODHSXBRWODHSGDHSODHSOFHSODHSODHSPJxSEDHSSM0SODHWSD0SODHSODHSOETqODHSPFHSODHSc' , "
        $s3 = "'nHWPDJqODHSODHS3DHAODHSODHSPFJqEHHyODHSODHSADHS3DHSODHSOLHySEHAODHSODHSRDHSEDHSODHSOEJyQ' , "
        $s4 = " $register_key = array "
        $s5 = "'FHSRDHALDISODIyWHHIQDHSODHSOH0SOq0ShM0IODHSODHSODHSODHSOFHSODHSYZRWODHSODHSODHSODHSOD0SO' , "
        $s6 = "'DHSODGEODHSODIIODHSOEHSODHSOq0SODHWEDxSODIIaHISWExySEHAPGHSODHSHDHSODHWODHSODHIODHSODxSO' , "
        $s7 = " * Version settings"
        $s8 = "'DHSODHSODz5ODHSOD1SODHSOFHSODHSAM3qEFHEOGHSODJqODHSOEHSODHSODHSODHSEDHSODHyODHSOL0SODHSO' , "
        $s9 = "\"\\x20\\x2e\\x20\\x62\\x61\\x73\\x65\\x36\\x34\\x5f\\x64\\x65\\x63\\x6f\\x64\\x65\\x20\\x28\" . "
        $s10 = "/*Ending*/"
        $s11 = "<?php "
        $s12 = "array"
condition:
    uint16(0) == 0x5a4d and filesize < 90KB and
    4 of them
}
    
